FROM nginx:alpine

COPY nodeappassignment.crt /etc/ssl/certs/nodeappassignment.crt
COPY nodeappassignment.key /etc/ssl/private/nodeappassignment.key
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
