FROM nginx:alpine

RUN apk add --no-cache openssl \
  && mkdir -p /etc/ssl/private /etc/ssl/certs \
  && openssl req -x509 -nodes -days 365 \
    -newkey rsa:2048 \
    -subj "/C=US/ST=State/L=City/O=NodeApp/CN=nodeappassignment.com" \
    -keyout /etc/ssl/private/nodeappassignment.com-rapidssl.key \
    -out /etc/ssl/certs/nodeappassignment.com-rapidssl.crt

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
